### ISSUE TITLE
Add create-satellites-function

### ISSUE THREAD

**Issue by bokusunny** [BuddiX/orbit-app#25]
## 概要
衛星機能の実装
## その他
割とめんどくさそう
優先順位高くない(最悪なくても)

**Comment by rechtburg** [comment]
subassignmentのDB構造とともに、
根が深い問題で、
この実装はシステムを根本的に抜本改革しないと、ただのバグの温床になるので、フロントでの実装はペンディング
将来的な実装の可能性は捨てていない
