### ISSUE TITLE
Test deploy

### ISSUE THREAD

**Issue by Taishi-M-UTMafia** [BuddiX/orbit-app#27]
## 概要
デプロイ用のブランチを作ってHerokuに現状をデプロイしてみる。
明日のMTGまでのどこかで。履歴ページ作り終えたくらいのタイミングがいいかな。
## 背景
そろそろしておかないとあとあと面倒臭そう
## URL
https://orbit7.herokuapp.com/

**Comment by yuki-s-utmafia** [comment]
@Taishi-M-UTMafia 
これてことは、明日のMTGまでに履歴までおおよそできてた方がいいってことよね？笑

**Comment by Taishi-M-UTMafia** [comment]
あ、テストだしできるところまでで大丈夫！
機能面での話です
