### ISSUE TITLE
SNS認証つける

### ISSUE THREAD

**Issue by Taishi-M-UTMafia** [BuddiX/orbit-app#81]
## 概要
- Twitter
- Facebook
- github
- gmail

**Comment by Taishi-M-UTMafia** [comment]
@yuki-s-utmafia 
これ個人的に実装したいんだけど、デザイン的にはこの前言ってた背景の星を一部ボタンにするみたいなのがいいのかな？

**Comment by yuki-s-utmafia** [comment]
今回のAppでは見送り、issueとして残す必要性がなくなったのでクローズ
