### ISSUE TITLE
星にcheckつけるとこを画像からCSSに変更

### ISSUE THREAD

**Issue by Taishi-M-UTMafia** [BuddiX/orbit-app#88]
<img width="98" alt="2018-11-11 4 34 11" src="https://user-images.githubusercontent.com/39128496/48305279-1ae0c680-e56b-11e8-9c16-7f77eba3369b.png">

## 概要
- 現状星を選択する時いちいち画像を差し替えているので、そこをCSSで実装
- check時にもう一度ClickするとUnselectできるように
## URL
`mypage.js` , `project-page.js` , `history-page.js`

**Comment by yuki-s-utmafia** [comment]
これの詳細要件もとむ

**Comment by Taishi-M-UTMafia** [comment]
@yuki-s-utmafia 
上のように星に選択したFlgを建てる時、現状いちいち画像をimportして差し替えていると思うんだけど、ここを動的なCSSの変更で表現したい
